### ISSUE TITLE
Add additional information on Syshub Proposal details

### ISSUE THREAD

**Issue by Keyare** [syscoin/syshub#13]
From Forum: 
a) Issue:
What is lacking from SYShub is a way to see who proposed the proposals.
Also their ID and where the funds go.
I could just create a proposal which looks like it's funding scmt and funnel the funds into my own addresses and people wouldn't really be able to tell from the website
Solution: 
a)  If exists, show SYShub USRname, else use syscoin funding address.
b) Show payout address

b) Also, 
Issue: "Status: UNFUNDED - Insufficient Votes 28/1031" isn't really informative. 
Solution:  "Insufficient Votes N/M required of T total"

**Comment by einalex** [comment]
I approve of this improvement proposal.






:D

**Comment by cortesa** [comment]
okay, noted

**Comment by cortesa** [comment]
bullet a - finished (deployment pending until all are finished)
