### ISSUE TITLE
links to proposals dont work

### ISSUE THREAD

**Issue by sidhujag** [syscoin/syshub#2]
https://syshub.org/p/72deb7a7ec1a4a31b3f5ed4ced0be7b77405d705982d55a0defee9adae3db2e7

that is a link to the most recent proposal which shows blank page when you click.

**Comment by cortesa** [comment]
Fixed

**Comment by cortesa** [comment]
The problem are that this proposal has expired, but the app doesn't show anything, now it show a modal telling you the proposal has expired and redirect to home.
