### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by johnp1954** [syscoin/syshub#24]
If you choose to vote and have multiple MNs a dialog pops up asking to confirm, if you press cancel your votes are still counted

**Comment by cortesa** [comment]
do you mean this modal?
![image](https://user-images.githubusercontent.com/11801422/60755572-e33ef700-9ff1-11e9-8ab6-82b2954eb38b.png)

**Comment by cortesa** [comment]
Since this modal is only for info it doesn't make sense to have a cancel button so I removed it

**Comment by cortesa** [comment]
if it isn't the modal you refer feel free to reopen it with a screenshot to locate it, thanks for you feed back
