### ISSUE TITLE
Proposal End times are off

### ISSUE THREAD

**Issue by bigpoppa-sys** [syscoin/syshub#3]
Problems with Generator and epoch times
1. The end dates are before Superblock.
2. The start dates are right on Voting deadline dates

Solution. +/- epoch times 5-10 before and after Superblock/Deadline dates.

As you can see below for proposal it starts on the 27th, which is the voting deadline, and ends on the 27th July. It will receive the first payment, but miss out on the second, as superblock would be scheduled for +/- a day August 1st. It may miss out entirely if it doesn't initiate before the voting deadline.

edit: The starting date seems to be a display issue. From QT/cli, starting date is ok.

![syshub-issue](https://user-images.githubusercontent.com/48267173/59495005-c2dbbb00-8ed1-11e9-8b45-7f17fe34bc10.png)

**Comment by cortesa** [comment]
**Fixed** 
- The proposal detail show the `Start Date` correctly
- The proposal creation have been modified to take today as Start Date, there is no sense to fix the starting date in the future when the chain doesn't take it in to account.
- The `End Date` for the proposal is set after the last superblock payout date and the first payment option take into account today date:
 -- 1) if today is before voting deadline it takes the next payout date
 -- 2) if today is after or equal voting deadline it takes the payout date after the next one.  

![IMG_E5F230A75054-1](https://user-images.githubusercontent.com/11801422/59877405-16ed1080-93a6-11e9-9a73-971896df2ae1.jpeg)
