### ISSUE TITLE
1 month proposal still there after payout occurs and indicates XX days remaining

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syshub#37]
Dates seem confusing, not sure why it says 9 days remaining when the payout has already occurred, it was a 1 time payment proposal.
![image](https://user-images.githubusercontent.com/7034589/60748205-74ae5a80-9f59-11e9-9362-71b75df0eab9.png)

**Comment by Keyare** [comment]
The user was prompted to manually enter start date and end date in the version of SYShub that that proposal was made on.  The user needed to add extra days to the proposal to ensure that the Superblock date was covered in case of changing difficulty/times.

This has been changed to exact block height and number of payouts in the latest version of SYShub, which is already live.
